### ISSUE TITLE
change highlight url to local Zotero

### ISSUE THREAD

**Issue by Lucasgong** [e-alizadeh/Zotero2Readwise#17]
great job!

I use this in obsidian workflow as you posted in [workflow](https://forum.obsidian.md/t/zotero-zotero2readwise-python-library-readwise-workflow/29798)

I has some suggestion:

1. Readwise highlight url points to an link to Zotero local app rather than web. So we can use url in Obsidian to open Zotero pdf .
2. metadata url is zotero url, can change it to local pdf file

**Comment by e-alizadeh** [comment]
Thanks a lot for the suggestions :) 
I really like the suggestion. Will definitely investigate it.

Could you please elaborate more on your 2nd suggestion? How is that different from the 1st suggestion?
What is metadata url?

**Comment by davidszp** [comment]
I took a look at this and it appears the item ID is different for the same PDF file depending on if it is hosted in the standard Zotero cloud or locally or ones on NAS system via WEBDAV.

Is there a way to get the latter local ID instead of the Zotero cloud ID? Then the annotation URL at the end of each highlight sent to Readwise could easily be created as `zotero://select/library/items/[local_or_WEBDAV_ID]`

**Comment by davidszp** [comment]
Editing row 113 in readwise.py yields the desired zotero:// link to be transferred to readwise:

`#highlight_url=annot.annotation_url,`
`highlight_url='zotero://select/library/items/'+annot.source_url.split('/')[6],`

Using this, readwise highlights will point directly to the zotero app e.g. `zotero://select/library/items/H3XQEFMZ`. Maybe this could be added as an optional feature for those users who do not use Zotero cloud storage but use Webdav or local storage instead.

**Comment by floriankilian** [comment]
Hey!
This might be possible to implement now? Zotero added support for links like 

zotero://select/library/items/****
zotero://open-pdf/library/items/**** (did not work for me yet, but could be an iOS problem)

- at least from external apps, as Obsidian/Notion/Readwise would be.


https://forums.zotero.org/discussion/99398/links-to-pdfs-work-on-mac-but-not-on-ios#latest 
https://github.com/zotero/zotero-ios/issues/316

**Comment by e-alizadeh** [comment]
The feature is now available in [v0.3.0](https://github.com/e-alizadeh/Zotero2Readwise/releases/tag/v0.3.0).
