### ISSUE TITLE
Only sync pre-specified color(s)?

### ISSUE THREAD

**Issue by deklanw** [e-alizadeh/Zotero2Readwise#25]
It would be convenient to have a highlight color which signifies "I want this to be synced to Readwise". In my case, most of my highlights aren't review-worthy in a generalized context outside of whatever research I'm doing. Some small amount are.

![image](https://user-images.githubusercontent.com/11601778/166176293-9f318ccc-1640-438a-8c56-5c805ce45cb1.png)

I imagine most people don't use all of the available options anyway.

**Comment by e-alizadeh** [comment]
The feature is now available in [v0.3.0](https://github.com/e-alizadeh/Zotero2Readwise/releases/tag/v0.3.0).

Thanks @noeleont for the contribution.
