### ISSUE TITLE
Partial push of highlights to Readwise

### ISSUE THREAD

**Issue by e-alizadeh** [e-alizadeh/Zotero2Readwise#40]
Currently, the library fetches all Zotero highlights/notes and pushes them to Readwise each time. 

For efficiency and also in order to avoid any potential duplicated highlights due to either library changes or changes in Readwise de-duplication algorithm, the library should be able to push only latest highlights.

This is related to the [issue #31](https://github.com/e-alizadeh/Zotero2Readwise/issues/31).

**Comment by EdSplendor** [comment]
Are you working on this enhancement?

Would it be possible to fetch highlights/notes only from a specific Zotero Collection?

**Comment by e-alizadeh** [comment]
I didn't work on it since there was not enough interests for it. The other reason is that it's not a big deal IF THERE IS NOT SIGNIFICANT API change as Readwise is very good at detecting duplicates. 

I took a quick look at the API, it seems possible. This actually might be simpler than the partial push of highlights. Let me check if I can get this working for you in the next few days.

**Comment by e-alizadeh** [comment]
@EdSplendor Sorry to be a bit late here, but I haven’t finished this yet. Unfortunately, I might not be able to work on this at the moment.

For my future self!: the related API to return Zotero collection specific items can be found [here](https://pyzotero.readthedocs.io/en/latest/#retrieving-collections).

**Comment by EdSplendor** [comment]
Thanks for getting back to me. Could you push the branch you are working on?
May be I could help out if I find time and try my luck...
However, I'm not a very experienced coder...
