### ISSUE TITLE
Zotero Annotations/Notes Failed to Format

### ISSUE THREAD

**Issue by BrianWBauer** [e-alizadeh/Zotero2Readwise#68]
I receive the below message after running the script provided. The can see the 2/9 that didn't fail in my Readwise account. 

NOTE: 7 Zotero annotations/notes (out of 9) failed to format.
You can run `save_failed_items_to_json()` class method to save those items.

Here is an example of what I see in my json file: 

        "meta": {},
        "data": {
            "key": "UIY4CRAT",
            "version": 1612,
            "parentItem": "DT44V28V",
            "itemType": "annotation",
            "annotationType": "highlight",
            "annotationText": "The basis of psychological targeting draws on selfregulatory goal-directed conceptualizations of personality, broadly known as cybernetic theories (e.g., Allport, 1937; Carver, 1979; DeYoung, 2015; Fleeson & Jayawickreme, 2015; Fleeson & Wilt, 2010; O. P. John et\u00a0al., 2010; McAdams & Pals, 2006; Revelle & Condon, 2015; Van Egeren, 2009). According to cybernetic theory, humans constantly compare their current states to their desired states (i.e., their goal states). If there is a mismatch between the two, then individuals adjust their behaviors and actions to close the gap. In such a system, predisposing tendencies\u2014such as personality traits\u2014allow humans to dynamically adapt to situations (Rauthmann et\u00a0 al., 2014). Thus, personality traits, beliefs, and motivational tendencies are useful for psychological targeting because they are the building blocks of a particular person\u2019s cybernetic system that allows them to better adapt to situations.",
            "annotationComment": "",
            "annotationColor": "#ffd400",
            "annotationPageLabel": "2",
            "annotationSortIndex": "00001|003198|00271",
            "annotationPosition": "{\"pageIndex\":1,\"rects\":[[322.5,500.47,555.02,511.48],[310.5,488.47,555.17,499.48],[310.5,476.47,555.59,487.48],[310.5,464.47,555.52,475.48],[310.5,452.47,555.03,463.48],[310.5,440.47,555.24,451.48],[310.5,428.47,554.83,439.48],[310.5,416.47,555.05,427.48],[310.5,404.47,554.98,415.48],[310.5,392.47,555.32,403.48],[310.5,380.47,554.86,391.48],[310.5,368.47,555.42,379.48],[310.5,356.47,555.09,367.48],[310.5,344.47,555.41,355.48],[310.5,332.47,554.79,343.48],[310.5,320.47,555.23,331.48],[310.5,308.47,555.04,319.48],[310.5,296.47,493.51,307.48]]}",
            "tags": [],
            "relations": {},
            "dateAdded": "2023-12-01T18:15:55Z",
            "dateModified": "2023-12-01T18:15:55Z"
        }
    },
    {

**Comment by jmhammond** [comment]
I wanted to add a comment that this is happening to me as well. I'm a new user of the script.

I'm running Zotero 7 beta if that helps with diagnosing the issue.

**Comment by jmhammond** [comment]
I found the error! Your metadata is missing the "attachment_url" (so I mine).  I've documented it in #70 and proposed a fix with #71's pull request.

**Comment by e-alizadeh** [comment]
Thanks @jmhammond for your contribution. I didn't have any comment on the PR, so I merged it.
