### ISSUE TITLE
Hi, there is an 'ImportError'

### ISSUE THREAD

**Issue by CandiceChuDVM** [e-alizadeh/Zotero2Readwise#73]
ImportError: cannot import name 'write_library_version' from 'zotero2readwise.helper' (/Users/username/miniconda/lib/python3.9/site-packages/zotero2readwise/helper.py)

**Comment by CandiceChuDVM** [comment]
Tried Approach 2 (through python terminal) and that works for me!

**Comment by e-alizadeh** [comment]
@CandiceChuDVM Glad Approach 2 worked. 

I can't recreate this issue. I believe the `ImportError` you're seeing has to do with environment setup. Having said that, I'm pushing a change in the next release. Hopefully that will work.

**Comment by e-alizadeh** [comment]
@CandiceChuDVM Glad Approach 2 worked. 

I can't recreate this issue. I believe the `ImportError` you're seeing has to do with environment setup. 
Having said that, I've pushed an update in the latest release (v0.4.5) that might resolve the issue you are facing when trying Approach 1. For that, please delete your current environment and recreate it using the latest release. 

Feel free to reopen this ticket if the issue persists.
