### ISSUE TITLE
run.py -h says notes are included by default by they aren't

### ISSUE THREAD

**Issue by cabahrdtnet** [e-alizadeh/Zotero2Readwise#74]
When running `run.py -h` in version 0.4.4, `run.py` tells users that notes are included by default. However, they are not.

The reason for this is simply that the help parameter for the corresponding argument says so:
`        help="Include Zotero notes | Options: 'y'/'yes' (default), 'n'/'no'",`
[Line 36 of run.py at 18715da](https://github.com/e-alizadeh/Zotero2Readwise/blob/18715da7b6eeee345a6d7cf23f99616f0d8e193e/zotero2readwise/run.py#L36)

But the default parameter is set to 'n':
`        default="n",`
[Line 35 of run.py at 18715da](https://github.com/e-alizadeh/Zotero2Readwise/blob/18715da7b6eeee345a6d7cf23f99616f0d8e193e/zotero2readwise/run.py#L35)

As I am a rather new user of Zotero2Readwise, I can only assume I would have expected a `default="y"` here, so that the user isn't surprised that certain data has not been exported to Readwise. But, if this is a deliberate choice, then the help string should be adapted.

**Comment by e-alizadeh** [comment]
Thanks @cabahrdtnet for raising this issue. I've updated the help.
FYI, the default argument is set to `n`, so the default setting does not include annotations unless specifically asked to be included.

**Comment by cabahrdtnet** [comment]
You're most welcome, thanks for fixing this.
